# Generated by Django 5.2.5 on 2025-08-31 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('application_date', models.DateField()),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Offer Received', 'Offer Received'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Applied', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('link_to_posting', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-application_date', '-updated_at'],
            },
        ),
    ]
